### ISSUE TITLE
Does not work for term usage without `set termguicolors`

### ISSUE THREAD

**Issue by ccharly** [flrnd/candid.vim#4]
Hi there, wonderful colorscheme :) however it seems that the current README isn't metionning any use of `set termguicolors`. In order to make it work with my setup, I had to add this to my `.vimrc`. It might be related to my setup but I was thinking it was a good idea to mention it directly in the `README`. WDYT? Thanks. :)

**Comment by flrnd** [comment]
Hey, @ccharly thanks for the heads up. You are right, I think it's a good idea. I assumed it that everyone has that by default and I was wrong :).
