### ISSUE TITLE
Not able to see the current selection when doing string search & replacement

### ISSUE THREAD

**Issue by alabeduarte** [flrnd/candid.vim#6]
Hi there!

First of all, thank you for this theme, it is great and I've been using it for 3 months and I'm loving it!

I have a question about the colour palette, not sure if this is my settings or this is something that can be tweaked by `candid.vim`.

When I want to do perform string replace commands I can't see at a glance which is the **current** since all have the same colours.

Here's an example, given I have the following text:

```
abcdefg

ascoabcanscoinasic
```

Then, I run the following command:

```vim
:%s/abc/ABC/gc
```

This is what I see:

![image](https://user-images.githubusercontent.com/418269/93168833-2143b900-f767-11ea-84e2-8b463813c480.png)

Using a different colour scheme, this is how it is displayed (please note that in "grey" is the **current selection**):

![image](https://user-images.githubusercontent.com/418269/93169091-afb83a80-f767-11ea-97f6-4ba83f47ce7e.png)

Cheers!

**Comment by flrnd** [comment]
Hey! I'm glad you like it!
The thing is that as far as I know, there is no built-in option that allows to highlight the current search selection. In orther to do that I'd had to match with reg expresions the search, but I may be doing something wrong too, Can I ask, what colorscheme is that example? So I can ~~shamely steal~~ have more info about how to resolve this.

Cheers!

**Comment by alabeduarte** [comment]
Hi @flrnd 

In the example, I'm actually using the default that comes with the OS (Mac OSX). The fact it is dark is because I'm using iterm2 with the "solarized" theme.

I checked the colour scheme from iterm and it doesn't seem to be affecting `candid.vim` colour schemes though (i.e. don't see any "mustard" there):
![image](https://user-images.githubusercontent.com/418269/93203112-27ea2480-f797-11ea-96d6-bc1b433b65be.png)


From other themes I've used in the past, I don't recall to have this issue. The previous I was using was [altercation/vim-colors-solarized](https://github.com/altercation/vim-colors-solarized), not sure if it helps 😄

**Comment by flrnd** [comment]
I found the problem, I had `IncSearch` with the same color definition as `Search`.

For a moment I thought the problem was more complex and you were refering to the current cursor position when you do a search.

Updating the colorscheme should fix your problem.
Cheers!

**Comment by alabeduarte** [comment]
Thanks @flrnd 

So when you say updating the colours scheme you mean overwrite my current setting or you mean changing raising a PR with the changes?

**Comment by alabeduarte** [comment]
Oh, nevermind, just saw you updated it with https://github.com/flrnd/candid.vim/commit/f3ca84559589f48531c77330ed11bd1abee9aecb

Thank you so much!

![image](https://user-images.githubusercontent.com/418269/93274353-834efd80-f7fd-11ea-9423-85b07b3c32e3.png)
