### ISSUE TITLE
filetype `diff` is hard to read

### ISSUE THREAD

**Issue by roblevy** [flrnd/candid.vim#9]
The colours for diffs are a bit hard to read, at least on my setup. I like the convention of "green=added, red=deleted".

## Minimum working example

Start with a blank document. Do `:setfiletype diff` then type:

```diff
+ Additions
- Deletions
```

The resulting dark-blue-on-black for the removal is hard to read. Can we revisit these colours?

![diff mode](https://user-images.githubusercontent.com/4764631/104443693-a8c2fc80-558e-11eb-91bd-a3c4b420b7b8.png)

**Comment by roblevy** [comment]
My bad. I had these lines _after_ specifying my colour scheme

```
syntax enable
set termguicolors
```

Sorry about that.

**Comment by flrnd** [comment]
Hey @roblevy, no worries.
